get_filename_component(OP_ROOTDIR ${CMAKE_CURRENT_LIST_DIR}/../.. ABSOLUTE)
get_filename_component(OP_ROOTDIR ${OP_ROOTDIR} ABSOLUTE) # remove relative parts
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/opfunmac.cmake)
  include(${CMAKE_CURRENT_LIST_DIR}/opfunmac.cmake)
elseif(EXISTS ${OP_ROOTDIR}/share/cmake/opfunmac.cmake)
  include(${OP_ROOTDIR}/share/cmake/opfunmac.cmake)
else()
  message(FATAL_ERROR "Could not find opfunmac.cmake")
endif()
link_directories(${OP_ROOTDIR}/lib)
include_directories(SYSTEM ${OP_ROOTDIR}/include)
# TODO: append to the cmake module path (issue with spaces in path and cmake's check_type_size?)
#list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
list(APPEND OP_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
